spring:
  boot:
    admin:
      client:
        url: http://172.16.2.193:8081
  datasource:
    url: jdbc:mysql://172.16.4.159:3306/oomall?serverTimezone=GMT%2B8
    username: dbuser
    password: 123456
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*
  redis:
    # Redis服务器地址
    host: 172.16.2.193
    # Redis服务器连接端口
    port: 6379
