
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oomall?serverTimezone=GMT%2B8
    username: dbuser
    password: 123456
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*
  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码
    password: 123456
      #mail:
      #host: smtp.qq.com
      #port: 587
      #username: 925882085@qq.com
      #password: lwjlfkksssdnbbhj
      #default-encoding: UTF-8
      #properties:
      #mail:
      #smtp:
      #socketFactory:
      #class: javax.net.ssl.SSLSocketFactory
      #debug: true

      #cloud:
      #nacos:
      #discovery:
    #server-addr: 172.16.1.87:8848